### PR TITLE
Test 007: EXTRA_DOCKER_STORAGE_OPTIONS

### PR DESCRIPTION
**Pull request by stephen679**
Adding a test case for extra docker storage options, and seeing if user config inputs are reflected after docker-storage-setup runs.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
You introduced helper function vg_exists() but did not make use of it in test?

**Comment by stephen679** [comment]
I did for test 007, I want to merge the helper before applying all the changes for tests 1-6

**Comment by rhvgoyal** [comment]
Actually introduce helper first and then use it in test7, that would be better. 

In fact, it would be better that open a PR where you introduce helper vg_exists and move all the existing tests to make use of this helper. Once that is merged, open separate PR for test 7.

**Comment by stephen679** [comment]
@rhvgoyal see PR #143

**Pull request closed without merging**
