### PR TITLE
[merged] Add support for overlay2 graph driver

### PR DESCRIPTION
**Pull request by rhvgoyal**
Right now docker-storage-setup does not allow specifying overlay2 as storage driver. Docker supports it. So start supporting overlay2 as well.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
cc @rhatdan @cgwalters

**Comment by rhatdan** [comment]
LGTM

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ d220103

**Comment by rhatdan** [comment]
@lsm5 We need a newer version of docker-latest-storage-setup

**Pull request closed without merging**
