### PR TITLE
[merged] Move Cleanup function to be shared between test scripts

### PR DESCRIPTION
**Pull request by rhatdan**
No need to share this code between tests

### CODE REVIEW

**Comment by rhatdan** [comment]
Yanked cleanup patch into its own pull request 
https://github.com/projectatomic/docker-storage-setup/pull/128

**Comment by rhatdan** [comment]
@rhvgoyal @cgwalters PTAL

**Comment by rhvgoyal** [comment]
You seem to have again pushed the whole patch (instead of just test related cleanup).

**Comment by rhatdan** [comment]
Oops try again.

**Comment by rhvgoyal** [comment]
Is something wrong with CI. Test job has not completed yet and generally it finishes pretty fast.

**Comment by rhatdan** [comment]
@cgwalters @jlebon Could you guys kick the Jenkins server, seems to be hung.

**Comment by cgwalters** [comment]
bot, retest this please

**Comment by jlebon** [comment]
I see:

```
wipefs -a /dev/vdb
wipefs: error: /dev/vdb: probing initialization failed: Device or resource busy
```

**Comment by rhatdan** [comment]
@rhvgoyal Is the above failure caused by this patch?

**Comment by rhvgoyal** [comment]
It passed locally for me. So I doubt that this patch is causing this problem.

**Comment by rhvgoyal** [comment]
@jlebon If that message comes from wipefs in the prep section, that means /dev/vdb is busy and somebody has that device opened. A simple reboot of server might solve the issue. Otherwise we need to figure out who has /dev/vdb opened.

**Comment by jlebon** [comment]
@rhvgoyal Sounds good, will check it out in a few.

**Comment by jlebon** [comment]
bot, retest this please

**Comment by rhvgoyal** [comment]
@jlebon, thanks for fixing CI.

**Comment by jlebon** [comment]
@rhvgoyal NP, still not sure what caused it. My theory is that maybe we need a little delay between the `pvremove` and the `wipefs` in prep. We can investigate further if it happens again.

**Comment by rhvgoyal** [comment]
@jlebon, if delay is the issue, then a new job should succeed? But that did not seem to happen.

**Comment by rhvgoyal** [comment]
@cgwalters-bot r+

**Pull request closed without merging**
