### PR TITLE
WIP - Status output

### PR DESCRIPTION
**Pull request by mvollmer**
This is intended for driving a UI and provides information about
requested configuration vs actual configuration.

### CODE REVIEW

**Comment by mvollmer** [comment]
Docs, tests, and human readable output are still missing.

**Comment by mvollmer** [comment]
Docs added.  I'll wait for some feedback before taking this any further.

**Comment by mvollmer** [comment]
Does this make sense with the "overlay" storage driver?

**Comment by rhvgoyal** [comment]
I think it will be more useful to output status in the format that a human can read first. Then tools can either parse that or we could extend same to a machine readable format using some sort of switch.

**Comment by rhvgoyal** [comment]
At higher level when it comes to status/info, I would think of following items.
- Storage Driver

And then details specific to that storage driver. For devicemapper storage driver, following additional 
details should be helpful.

- Thin Pool Name and some properties like "state", size etc.

Being able to provide more details about devices seems low level. In first step, I think it should be
enough to just list the devices specified in DEVS?

**Comment by mvollmer** [comment]
> I think it will be more useful to output status in the format that a human can read first. Then tools can either parse that or we could extend same to a machine readable format using some sort of switch.

Without machine readable output, this change would not be useful to me, so we need to include that from the get go.

Thanks for the suggestions, I'll work on adding humane friendly output.

(Do you have a official way to mark this as 'work in process'?)

**Comment by rhvgoyal** [comment]
If storage driver is overlay, we should supress rest of the output. Something like "docker info" Where every storage driver gets to output its own status. So there are some generic fields and there are some driver specific fields.

**Comment by mvollmer** [comment]
@rhvgoyal, do you still think we need human readable output here?  Or should that be done via `atomic storage`?

**Comment by mvollmer** [comment]
I think goes to far, and I am not really working on this anymore.

**Pull request closed without merging**
