### PR TITLE
docker-storage-setup: Enable deferred device removal feature if available

### LINKED ISSUE #42: Enable deferred device removal feature in docker devicemapper graph driver
Docker 1.7 devicemapper graph driver now supports deferred device removal feature. That is if device backing image/container is busy, then docker will not wait for all device refcounts to be dropped. Instead docker will schedule a deferred a deferred removal on device. That is when last reference to
device is dropped, kernel will automatically remove the device.

Enable this feature by default if docker version supports it.

### PR DESCRIPTION
**Pull request by rhvgoyal**
Fixes #42 

Enable deferred device removal feature by default if docker version is
equal or higher than 1.7.

This feature will allow stopping container even if device is busy. Once
the last reference to device is dropped, device will automatically go away
and docker does not have to wait for it.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@cgwalters ping

**Comment by cgwalters** [comment]
The code looks as good as shell script can ;)

**Comment by rhatdan** [comment]
Lets make sure this DOES NOT get into docker-1.6.2 release.  @lsm5

**Comment by rhvgoyal** [comment]
@rhatdan 

Code detects the version dynamically and enables this feature only if docker version is greater than or equal to 1.7. So even if it gets into 1.6.2 accidently, I think it should cause on harm.

**Comment by lsm5** [comment]
@rhatdan @rhvgoyal no worries, the commit that went into 1.6.2 was #eefbef7

**Comment by lsm5** [comment]
which is the one before this commit

**Pull request merged**
