### PR TITLE
Add a README.md

### PR DESCRIPTION
**Pull request by cgwalters**
Every project should have one really.  Link to the man pages for now.

### CODE REVIEW

**Comment by cgwalters** [comment]
Let's merge this after https://github.com/projectatomic/docker-storage-setup/pull/108 so we can use Homu.

**Comment by rhatdan** [comment]
:+1:

**Comment by cgwalters** [comment]
@rhatdan Want to try out Homu?  Write in here: `@` `cgwalters-bot r+ 335ddba` with no space between `@` and the name.

**Comment by cgwalters** [comment]
Although you're not actually a reviewer yet, let me fix that...

**Comment by cgwalters** [comment]
fixed, also added @jwhonce

**Comment by rhatdan** [comment]
@cgwalters-bot r+335ddba

**Comment by rhatdan** [comment]
@cgwalters what was supposed to happen?

**Comment by cgwalters** [comment]
@rhatdan  Need a space between r+ and commit id

**Comment by rhvgoyal** [comment]
LGTM for the contents of PR.

**Comment by cgwalters** [comment]
So something that's interesting here is the Travis build for the branch fails because it isn't rebased yet.  However, the merge should work as that will automatically be rebased.  We'll see, one of you guys want to approve?

**Comment by rhatdan** [comment]
@cgwalters-bot r+ 335ddba

**Comment by rhatdan** [comment]
@cgwalters Pretty cool.

**Pull request closed without merging**
