### PR TITLE
[WIP]: Don't do anything if Docker already has data on loopback

### PR DESCRIPTION
**Pull request by cgwalters**
(This patch is not tested, submitting to gather comments)

If we want this service to start by default, it doesn't make sense to
try to allocate thinpool space if there are already Docker images on
loopback.  People would then just see their images/containers vanish.

Let's not do anything unless the system appears to be a clean slate.

For example, we also now silently do nothing if the user has
explicitly set a backend with `-s`, such as `-s overlayfs`.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
I personally feel that it should be docker who should detect that storage has changed from last time and bail out and force user to do cleanup.

docker-storage-setup is all about just setting up an lvm thin pool for docker user. It should not be in business of poking around whether what docker currently is using.

Also by setting up an lvm thin pool we don't lose any data. It is still present in the /var/lib/docker/ dir somewhere.

**Comment by rhvgoyal** [comment]
I do like the part where we make sure that nothing is configured in /etc/sysconfig/docker-storage though. That will protect us from few things.

- If user has edited this file, then we don't generate any thin pool. This will take care of the case of "-s overlay".
- If user has configured its own thin pool and using that, we will not generate our own and rewrite user
  configuration.

I think all the logic of grow root pvs will still get into the way. That is a misfit for this service. I am not sure are we still supposed to grow root pvs if we are not setting up thin volume. Growing root pvs seems to be orthogonal to setting up of storage for docker.

**Comment by rhvgoyal** [comment]
@cgwalters 

I modified your patches a bit and generated two patches. Please have a look.

**Comment by cgwalters** [comment]
This is obsolete.

**Pull request closed without merging**
