### PR TITLE
Bug 1261565 - Allow docker-storage-setup.sh to be run n-times

### PR DESCRIPTION
**Pull request by jwhonce**
* query the current volume groups and partitions to allow
  docker-storage-setup.sh to be idempotent

### CODE REVIEW

**Comment by jwhonce** [comment]
@rhvgoyal Please review.  Thanks.

**Comment by jwhonce** [comment]
@rhvgoyal Updated from your comments.

**Comment by rhvgoyal** [comment]
@jwhonce Can you please provide some description of the problem and how it is being fixed in the patch commit message.

**Comment by rhvgoyal** [comment]
I think we also need to prefix some kind of tag to messages to figure out what message is info and what message is warning and what message is error. For example, I ran docker-storage-setup and added an already partitioned disk and expected error. I see following on console.

`INFO: Volume group backing root filesystem could not be determined
Using existing /dev/sda1 partition
Device /dev/sdb is partitioned but missing /dev/sdb1 partition
`
In this case, first message is INFO and second is an ERROR. If we prefix it accordingly, one can easily figure out if script completed successfully or not. Just more intuitive logging.

**Comment by rhvgoyal** [comment]
@jwhonce I had commented on getting INFO and Error messages right. I don't see those changes in latest patches.

**Comment by rhvgoyal** [comment]
I had suggested the actual messages which I felt were much more clear then current once. Can't find these in this thread. Must have been in commit.

Also I had requrested for prefixing atleast "Error" or "ERROR" before actual error. Otherwise I can't differentiate between info and error. That change is also not there.

**Comment by jwhonce** [comment]
@rhvgoyal Try a refresh maybe?  Those changes are in commit d0580ca8b6e22f774aa09a2df7fc538f6d0c8d10

**Comment by rhvgoyal** [comment]
@jhwonce Ok, I see that new messages are in last patch of the series. Can we please modify first patch to put in the desired messages. It is never a good practice to first introduce a set of changes in first patch and revert these changes in 4th patch.

**Comment by rhatdan** [comment]
If you merge the patches into one, this is not a problem.  :8ball:

**Comment by rhvgoyal** [comment]
@rhatdan, sure. this is the extra overhead of breaking down changes into a patch series. If changes are requested, then one needs to figure out which patch is going to change and change that patch. Keeping everything in one patch simplifies that. But makes review harder.  So we gain some and loose some. I think it is just a matter of getting used to the workflow. I have come from a background where we always breakdown patches and john has always done everything in one patch and it is taking a bit to getting used to.

**Comment by rhvgoyal** [comment]
For future we can debate what's the patch convention we want for docker-storage-setup project. One patch vs broken down patch series. I personally think that we need to strike right balance. Too much of fine grained patches are not good and putting everything into a single patch is not good either (depending on amount of change).

**Comment by rhatdan** [comment]
@rhvgoyal Just joking....

**Comment by jwhonce** [comment]
@rhatdan @rhvgoyal Still striving for that happy medium, too much muscle memory in my fingers for amend'ing commits all into one. :-)

I believe this set of commits is what you are looking for @rhvgoyal

**Comment by rhvgoyal** [comment]
@jwhonce cool that you classified all the messages either as INFO or ERROR. This helps a lot.

This patch set now looks good to me except one minor nit. I don't think we should add idea IDE generated files into the docker-storage-setup project. Generally a project carries files in .gitignore which are generated by that project. Anything generated by other tools outside of the project, it is better to create a gloabl gitignore file. 

docker seems to follow the same thing. 

https://github.com/docker/docker/blob/master/.gitignore#L2

**Comment by jwhonce** [comment]
@rhvgoyal kubernetes uses a project .gitignore for these files to ensure they never get accidentally added.  I suspect this is personal/project style issue.

**Comment by rhvgoyal** [comment]
LGTM

**Comment by rhvgoyal** [comment]
@cgwalters Would you like to review this one before I merge it.

**Comment by jwhonce** [comment]
@cgwalters I fixed the error message.  I did not fix the test, as anything using bash arrays is a messier syntax.

**Comment by rhvgoyal** [comment]
@jwhonce do we really need bash arrays. Can't we simple run for loop on current_devices.

for d in $current_devices; do
done

**Comment by rhvgoyal** [comment]
@jwhonce @cgwalters I wrote a small patch on top of john's to replace using regexp for device mapthing. Does it look better.

https://github.com/rhvgoyal/docker-storage-setup/commit/ff5d3fb91c14be3392b2c492a0a842c537a5a2ea

**Comment by jwhonce** [comment]
@rhvgoyal Please echo the message to >&2. Thanks

**Comment by cgwalters** [comment]
rhvgoyal@ff5d3fb looks OK to me.  Squash into this commit and let's merge?

**Comment by rhvgoyal** [comment]
@jhwonce do you mind apply my patch on top of yours and push your patch again. Also please take care of outputting error message to stderr.

**Comment by jwhonce** [comment]
@rhvgoyal Done

**Comment by rhvgoyal** [comment]
@jwhonce Thanks. Merging it now.

**Comment by rhvgoyal** [comment]
@jwhonce looks like following code is not working. I passed in loop device /dev/sda1 and it is not detected as parition. 

  #validate DEVS elements
  for dev in $DEVS; do
    if [[ $dev =~ ".*[0-9]$" ]]; then
      echo "ERROR: Partition specification unsupported at this time." >&2
      exit 1
    fi

**Comment by rhvgoyal** [comment]
@jhwhonce

I think there is one more bug. I specified two devices in DEVS and only one device gets partitioned and gets added to volume group. one device remains untouched.

DEVS="/dev/sda /dev/sdb"
VG=foo-vg

**Comment by rhvgoyal** [comment]
I think issue is that variable name is not proper and one `s` is missing.

needs_partitioned="$dev $need_partitioned"

It should be

needs_partitioned="$dev $needs_partitioned"

**Pull request merged**
