### PR TITLE
docker-storage-setup: Ship an empty /etc/sysconfig/docker-storage-set…

### PR DESCRIPTION
**Pull request by rhvgoyal**
…up file

Fixes issue #55 

Jeremy complained that we ask users to modify
/etc/sysconfig/docker-storage-setup  and we don't ship one. He prefers that
we ship an empty one with additional information so that it is easier for
users to find it and edit it.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

### CODE REVIEW

**Comment by jeremyeder** [comment]
LGTM :+1: thanks for this, it should help direct users to the right place.

**Comment by rhvgoyal** [comment]
Added %config(noreplace) to this new file to make sure user's edited /etc/sysconfig/docker-storage-setup does not get overwritten.

**Comment by cgwalters** [comment]
OK.  However I'd recommend committing this to Fedora dist-git immediately as otherwise I suspect Lokesh could miss the changes to sources/Dockerfile here.

**Comment by rhvgoyal** [comment]
@lsm5 Ping.

**Comment by lsm5** [comment]
I should've seen this before I updated, anyway, re-updating now. Also, could you send future spec updates to the docker spec file itself. I'm hoping we can remove the spec file here: https://github.com/projectatomic/docker-storage-setup/pull/59

**Comment by rhvgoyal** [comment]
I think keeping a spec file in this project is important because that way a user knows how different files are to be installed and treated.

upstream docker does not have a spec file. Any changes to fedora docker spec file are specific to fedora only.

**Pull request merged**
