### PR TITLE
Add a travis file

### PR DESCRIPTION
**Pull request by cgwalters**
My primary goal here is just to enable Homu usage.

### CODE REVIEW

**Comment by cgwalters** [comment]
:warning:  Oops, meant to test this against *my* fork.  @rhvgoyal - don't merge this yet please! :warning:

**Comment by cgwalters** [comment]
@cgwalters-bot try

**Comment by cgwalters** [comment]
@cgwalters-bot retry

**Comment by cgwalters** [comment]
@rhvgoyal If you want to try this out, enter in text `@ cgwalters-bot r+ 245bcb6` with no space between @ and the name.

**Comment by rhvgoyal** [comment]
@cgwalters-bot r+ 245bcb6

**Comment by rhvgoyal** [comment]
@cgwalters-bot r+ 0be34df

**Comment by rhvgoyal** [comment]
@cgwalters why did I lose the link to my jenkins test results while I tried to run homu.

**Comment by cgwalters** [comment]
This is apparently because the PR was closed instead of known to github as merged.   See https://github.com/barosl/homu/pull/139

However, I think we can address this somehow.  One way would be for the PR tester to add a comment in addition to the status.  Another would be for homu to gather all successful links.

In general, an issue right now is we're only gating on travis, but we should probably consistently use the github status.  I'll look at that change too.

**Pull request closed without merging**
