### PR TITLE
tests: Use sfdisk if parted is not present

### PR DESCRIPTION
**Pull request by rhvgoyal**
Right now atomic host does not seem to include parted. In that case use
sfdisk to remove partitions.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

### CODE REVIEW

**Comment by rhvgoyal** [comment]
cc @jlebon

**Comment by jlebon** [comment]
Strange indeed. I can't reproduce this when running on OpenStack just like the tester.
Could you try adding a `udevadm settle` in case it is indeed udev?

**Comment by jlebon** [comment]
Ahh, I did get it to reproduce, but on another test. Will check if `udevadm settle` makes it more reliable (otherwise, a simple retry loop should do the trick).

**Comment by jlebon** [comment]
This works for me:

```diff
diff --git a/tests/libtest.sh b/tests/libtest.sh
index bd407ae..cf55ce4 100644
--- a/tests/libtest.sh
+++ b/tests/libtest.sh
@@ -56,6 +56,11 @@ remove_partitions() {
 # Wipe all signatures on devices
 wipe_signatures() {
   local dev devs=$1
+
+  # wipefs triggers a partition table reload,
+  # so let's make sure we're stable first
+  udevadm settle
+
   for dev in $devs; do
     wipefs -a $dev >> $LOGS 2>&1
   done
```

Would be nice to turn on `set -e` in these scripts. It's a bit tricky to debug otherwise.

**Comment by rhvgoyal** [comment]
@jlebon, ok, using udevadm settble between remove_partition and wipefs seems reasonable. 

Or we could do.

- delete partition
- udevadm settle
- partprobe <disk>

But this again requires partprobe and that requires parted package which is missing on atomic host. 

So for now, it makes sense to let udev settle down before running wipefs. I will update my patch and test it and put your signed-off-by as well.

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 084a374

**Comment by rhvgoyal** [comment]
@jlebon, I am not sure if this commit fixed the problem. I was looking at logs and got the feeling that wipefs was still finding the device busy.

**Comment by rhvgoyal** [comment]
@jlebon is homu stuck? Generally it does not take this long to merge a PR.

**Comment by jlebon** [comment]
@rhvgoyal It's not configured properly for this repo. Will fix.

**Comment by jlebon** [comment]
@rh-atomic-bot retry

**Comment by jlebon** [comment]
@rhvgoyal I think those "Device or resource busy" messages are not coming from `wipefs` but maybe e.g. deleting partitions. The `wipefs` calls themselves seem clean:

```
/dev/vdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/vdb: calling ioctl to re-read partition table: Success
```

**Comment by rhvgoyal** [comment]
@jlebon Right. if we have waited for udev to settle down after partition deletion, wipefs reload partition table operation should be success.

**Pull request closed without merging**
